local cjson = require "cjson.safe"
local http = require "resty.http"
local pkey_lib = require "resty.openssl.pkey"
local random = require "resty.random"

local ASSERTION_TYPE = "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
local discovery_cache = {}
local cached_keys = {}

local function base64url(value)
  return ngx.encode_base64(value, true):gsub("%+", "-"):gsub("/", "_")
end

local function read_file(path)
  local file, err = io.open(path, "rb")
  if not file then
    return nil, err
  end

  local value = file:read("*a")
  file:close()
  return value
end

local function load_key(path)
  if cached_keys[path] then
    return cached_keys[path]
  end

  local pem, err = read_file(path)
  if not pem then
    return nil, "unable to read signing key: " .. tostring(err)
  end

  local key
  key, err = pkey_lib.new(pem)
  if not key then
    return nil, "unable to parse signing key: " .. tostring(err)
  end

  cached_keys[path] = key
  return key
end

local function verify_discovery_issuer(conf)
  local cache_key = conf.discovery_endpoint .. "\0" .. conf.issuer
  local cached_until = discovery_cache[cache_key]
  if cached_until and cached_until > ngx.now() then
    return true
  end

  local client = http.new()
  client:set_timeout(conf.discovery_timeout)
  local response, err = client:request_uri(conf.discovery_endpoint, {
    method = "GET",
    ssl_verify = true,
    keepalive = true,
    headers = { Accept = "application/json" },
  })
  if not response then
    return nil, "unable to load OIDC discovery metadata: " .. tostring(err)
  end
  if response.status ~= 200 then
    return nil, "OIDC discovery returned HTTP " .. tostring(response.status)
  end

  local metadata, decode_err = cjson.decode(response.body)
  if not metadata then
    return nil, "unable to decode OIDC discovery metadata: " .. tostring(decode_err)
  end
  if metadata.issuer ~= conf.issuer then
    return nil, "configured issuer does not match OIDC discovery"
  end

  discovery_cache[cache_key] = ngx.now() + conf.discovery_cache_ttl
  return true
end

local function supplied_by_client()
  if kong.request.get_header("client_assertion")
      or kong.request.get_header("client_assertion_type") then
    return true
  end

  local query = kong.request.get_query()
  if query.client_assertion or query.client_assertion_type then
    return true
  end

  local body = kong.request.get_body()
  return body and (body.client_assertion or body.client_assertion_type) or false
end

local function create_assertion(conf)
  local tls_certificate, tls_err = read_file(conf.tls_certificate_file)
  if not tls_certificate or not tls_certificate:find("BEGIN CERTIFICATE", 1, true) then
    return nil, "Route B TLS certificate is unavailable: " .. tostring(tls_err)
  end

  local key, err = load_key(conf.private_key_file)
  if not key then
    return nil, err
  end

  local now = ngx.time()
  local nonce = random.bytes(32, true)
  if not nonce then
    return nil, "unable to generate assertion jti"
  end

  local header = cjson.encode({ alg = "PS256", kid = conf.key_id, typ = "JWT" })
  local payload = cjson.encode({
    aud = conf.issuer,
    exp = now + conf.assertion_ttl,
    iat = now,
    iss = conf.client_id,
    jti = base64url(nonce),
    sub = conf.client_id,
  })
  if not header or not payload then
    return nil, "unable to encode assertion"
  end

  local signing_input = base64url(header) .. "." .. base64url(payload)
  local signature
  signature, err = key:sign(
    signing_input,
    "sha256",
    pkey_lib.PADDINGS.RSA_PKCS1_PSS_PADDING,
    { "rsa_pss_saltlen:digest", "rsa_mgf1_md:sha256" }
  )
  if not signature then
    return nil, "unable to sign assertion: " .. tostring(err)
  end

  return signing_input .. "." .. base64url(signature)
end

local Bridge = {
  PRIORITY = 1060,
  VERSION = "0.1.0",
}

function Bridge:access(conf)
  if supplied_by_client() then
    return kong.response.exit(400, {
      error = "invalid_request",
      error_description = "client assertion parameters are generated by Kong Gateway",
    })
  end

  local issuer_valid, issuer_err = verify_discovery_issuer(conf)
  if not issuer_valid then
    kong.log.err("fapi-client-auth-bridge failed closed: ", issuer_err)
    return kong.response.exit(500, { error = "client_authentication_unavailable" })
  end

  local assertion, err = create_assertion(conf)
  if not assertion then
    kong.log.err("fapi-client-auth-bridge failed closed: ", err)
    return kong.response.exit(500, { error = "client_authentication_unavailable" })
  end

  -- The OpenID Connect plugin reads these request headers through
  -- token_post_args_client and sends them as token endpoint form parameters.
  ngx.req.set_header("client_assertion", assertion)
  ngx.req.set_header("client_assertion_type", ASSERTION_TYPE)
end

return Bridge
